version: "2.0"

services: 
  mysql_server:
    image: mysql
    environment: 
      - MYSQL_DATABASE=CRUD-application-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    container_name: CRUD_appl_mysql
  app:
    image: poonam3112/nodejs-crud-app-image:latest
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    environment: 
      - MYSQL_DATABASE=CRUD-application-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=CRUD_appl_mysql
    depends_on: 
      - mysql_server
